import { Container, Heading } from "@chakra-ui/react";
import Link from 'next/link'
export default function Home() {
  
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Container maxW='7xl' height='100vh' display={'flex'} justifyContent='center' centerContent >
        <Heading>
          Blog UI Coming Soon
        </Heading>
        <Link href="/admin" >
        <a>
          <Heading borderBottom={'3px solid black'}>
        Admin Page(Click Here)
          </Heading>
        </a>
        </Link>
      </Container>
     
    </>
  )
}
